name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          work_in_root_file_dir: ./paper/paper.tex
      - name: Upload PDF file
        uses: softprops/action-gh-release@v2
        with:
          files: ./paper/paper.pdf
