name: Build LaTeX document

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ./paper/paper.tex
          work_in_root_file_dir: true
      - name: Upload PDF file
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: GSM-paper
          files: ./paper/paper.pdf
